name: Roels World
favicon: null
layout_spectrum: 0.49519
typography_spectrum: 0.32429
title: The world of Roel
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2b233f'
    - '#ddc0ab'
    - '#cea589'
    - '#7b5051'
    - '#ad8169'
  brandStrength: 1
  lightness: 0.4375
  saturation: 0.625
  rhythmicContrast: 0
purpose: []
